version: '3.8'

services:
  yt-text:
    build:
      context: .
      dockerfile: Dockerfile
    image: yt-text:latest
    container_name: yt-text
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_DEBUG=true
      - APP_DATABASE_URL=sqlite+aiosqlite:///data/db.sqlite
      - APP_WHISPER_MODEL=base
      - APP_MAX_CONCURRENT_JOBS=3
      - APP_CACHE_ENABLED=true
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./cache:/cache
      - ./models:/models
      - ./logs:/logs
      - ./static:/app/static
      # For development - mount source code
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - yt-text-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  yt-text-network:
    driver: bridge