services:
  app:
    build:
      context: .
      target: runner
    image: yt-text:latest
    environment:
      - SERVER_PORT=8080
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=60s
      - IDLE_TIMEOUT=120s
      - DEBUG=true
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_RPM=60
      - LOG_DIR=/app/logs
      - DB_PATH=/app/data/urls.db
      - SCRIPTS_PATH=/app/scripts
      - VIDEO_PROCESS_TIMEOUT=30m
      - VIDEO_MAX_DURATION=4h
      - VIDEO_MAX_FILE_SIZE=104857600
      - WHISPER_MODEL=base.en
      - PYTHON_PATH=/app/.venv/bin/python
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge
