# docker-compose.prod.yml
services:
  app:
    build:
      context: .
      target: runner
    image: yt-text:latest
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      - DB_PATH=/tmp/urls.db # Changed to use /tmp
      - SERVER_PORT=8080
      - READ_TIMEOUT=120s
      - WRITE_TIMEOUT=300s
      - IDLE_TIMEOUT=120s
      - TRANSCRIBE_TIMEOUT=30m
      - RATE_LIMIT=1
      - RATE_LIMIT_INTERVAL=10s

      # Model Configuration
      - MODEL_NAME=tiny.en
      - SUMMARY_MODEL_NAME=facebook/bart-base

      # Python Environment
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/tmp
      - HF_HOME=/tmp
      - XDG_CACHE_HOME=/tmp
      - TORCH_HOME=/tmp

      # Resource Management
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32
      - MALLOC_ARENA_MAX=2
      - GOMAXPROCS=1
      - GOGC=20

      # Spaces Configuration
      - SPACES_ENABLED=true
      - SPACES_KEY=${SPACES_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
      - SPACES_REGION=nyc3
      - SPACES_ENDPOINT=https://nyc3.digitaloceanspaces.com
      - SPACES_BUCKET=yt-text
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1.8G
        reservations:
          cpus: "0.25"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
