services:
    app:
        build:
            context: ./app
        ports:
            - "8080:8080"
        volumes:
            - ./data:/root/data
        environment:
            - DB_PATH=/root/data/urls.db
        restart: unless-stopped
