services:
  app:
    build:
      context: .
      target: runner
      args:
        GOMEMLIMIT: 1024MiB
        GOGC: 10
        GOMAXPROCS: 1
      cache_from:
        - type=registry,ref=yt-text:latest
      cache_to:
        - type=inline
    image: yt-text:latest
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      - DB_PATH=/tmp/urls.db
      - SERVER_PORT=8080
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=60s
      - IDLE_TIMEOUT=120s
      - TRANSCRIBE_TIMEOUT=60m
      - RATE_LIMIT=1
      - RATE_LIMIT_INTERVAL=10s

      # Model Configuration
      - MODEL_NAME=tiny.en
      - SUMMARY_MODEL_NAME=facebook/bart-base

      # Python Environment
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - WHISPER_DOWNLOAD_ROOT=/tmp
      - NUMBA_CACHE_DIR=/tmp
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/tmp
      - HF_HOME=/tmp
      - XDG_CACHE_HOME=/tmp
      - TORCH_HOME=/tmp

      # Resource Management
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32
      - MALLOC_ARENA_MAX=1
      - MALLOC_TRIM_THRESHOLD_=100000
      - MALLOC_MMAP_THRESHOLD_=100000
      - PYTHONMALLOC=malloc
      - GOMAXPROCS=1
      - GOGC=10
      - OOM_SCORE_ADJ=500

    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:size=1G,noexec
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1.8G
        reservations:
          cpus: "0.25"
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    networks:
      - yt_text_net

networks:
  yt_text_net:
    driver: bridge
    internal: true
