services:
  app:
    build:
      context: .
      target: runner
    image: yt-text:latest
    environment:
      # Server Configuration
      - DB_PATH=/tmp/urls.db
      - SERVER_PORT=8080
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=60s
      - IDLE_TIMEOUT=120s
      - TRANSCRIBE_TIMEOUT=60m
      - RATE_LIMIT=5
      - RATE_LIMIT_INTERVAL=5s

      # Model Configuration
      - MODEL_NAME=base.en
      - SUMMARY_MODEL_NAME=facebook/bart-large-cnn

      # Python Environment
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - WHISPER_DOWNLOAD_ROOT=/tmp/models
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/tmp
      - HF_HOME=/tmp
      - XDG_CACHE_HOME=/tmp
      - TORCH_HOME=/tmp

    volumes:
      - ./app:/app/src
      - ./python/scripts:/app/scripts
      - ./static:/app/static
      - whisper_cache:/tmp/models

    tmpfs:
      - /tmp

    deploy:
      resources:
        reservations:
          memory: 2G

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "8080:8080"
      - "2345:2345"

    networks:
      - yt_text_dev

volumes:
  whisper_cache:

networks:
  yt_text_dev:
    driver: bridge
    name: yt_text_dev
