# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transcribe_pb2 as transcribe__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transcribe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranscriptionServiceStub(object):
    """TranscriptionService defines the gRPC service for video transcription
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/transcribe.TranscriptionService/Validate',
                request_serializer=transcribe__pb2.ValidateRequest.SerializeToString,
                response_deserializer=transcribe__pb2.VideoInfo.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_stream(
                '/transcribe.TranscriptionService/Transcribe',
                request_serializer=transcribe__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=transcribe__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.FetchYouTubeCaptions = channel.unary_unary(
                '/transcribe.TranscriptionService/FetchYouTubeCaptions',
                request_serializer=transcribe__pb2.CaptionRequest.SerializeToString,
                response_deserializer=transcribe__pb2.TranscribeResponse.FromString,
                _registered_method=True)


class TranscriptionServiceServicer(object):
    """TranscriptionService defines the gRPC service for video transcription
    """

    def Validate(self, request, context):
        """Validate checks if a video URL is valid and can be processed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Transcribe starts a video transcription and streams progress updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchYouTubeCaptions(self, request, context):
        """FetchYouTubeCaptions retrieves captions from YouTube API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=transcribe__pb2.ValidateRequest.FromString,
                    response_serializer=transcribe__pb2.VideoInfo.SerializeToString,
            ),
            'Transcribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=transcribe__pb2.TranscribeRequest.FromString,
                    response_serializer=transcribe__pb2.TranscribeResponse.SerializeToString,
            ),
            'FetchYouTubeCaptions': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchYouTubeCaptions,
                    request_deserializer=transcribe__pb2.CaptionRequest.FromString,
                    response_serializer=transcribe__pb2.TranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transcribe.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transcribe.TranscriptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService(object):
    """TranscriptionService defines the gRPC service for video transcription
    """

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transcribe.TranscriptionService/Validate',
            transcribe__pb2.ValidateRequest.SerializeToString,
            transcribe__pb2.VideoInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/transcribe.TranscriptionService/Transcribe',
            transcribe__pb2.TranscribeRequest.SerializeToString,
            transcribe__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchYouTubeCaptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transcribe.TranscriptionService/FetchYouTubeCaptions',
            transcribe__pb2.CaptionRequest.SerializeToString,
            transcribe__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
