# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcribe.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transcribe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10transcribe.proto\x12\ntranscribe\"\x1e\n\x0fValidateRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"X\n\tVideoInfo\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x10\n\x08\x64uration\x18\x02 \x01(\x01\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\"\xa9\x01\n\x11TranscribeRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x1a\n\x12\x65nable_constraints\x18\x02 \x01(\x08\x12;\n\x07options\x18\x03 \x03(\x0b\x32*.transcribe.TranscribeRequest.OptionsEntry\x1a.\n\x0cOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd0\x01\n\x12TranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x01\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x10\n\x08language\x18\x06 \x01(\t\x12\x1c\n\x14language_probability\x18\x07 \x01(\x01\x12\x0e\n\x06source\x18\x08 \x01(\t\x12\x10\n\x08progress\x18\t \x01(\x01\x12\x16\n\x0estatus_message\x18\n \x01(\t\"3\n\x0e\x43\x61ptionRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t2\xff\x01\n\x14TranscriptionService\x12@\n\x08Validate\x12\x1b.transcribe.ValidateRequest\x1a\x15.transcribe.VideoInfo\"\x00\x12O\n\nTranscribe\x12\x1d.transcribe.TranscribeRequest\x1a\x1e.transcribe.TranscribeResponse\"\x00\x30\x01\x12T\n\x14\x46\x65tchYouTubeCaptions\x12\x1a.transcribe.CaptionRequest\x1a\x1e.transcribe.TranscribeResponse\"\x00\x42\x1bZ\x19yt-text/protos/transcribeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcribe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031yt-text/protos/transcribe'
  _globals['_TRANSCRIBEREQUEST_OPTIONSENTRY']._loaded_options = None
  _globals['_TRANSCRIBEREQUEST_OPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_VALIDATEREQUEST']._serialized_start=32
  _globals['_VALIDATEREQUEST']._serialized_end=62
  _globals['_VIDEOINFO']._serialized_start=64
  _globals['_VIDEOINFO']._serialized_end=152
  _globals['_TRANSCRIBEREQUEST']._serialized_start=155
  _globals['_TRANSCRIBEREQUEST']._serialized_end=324
  _globals['_TRANSCRIBEREQUEST_OPTIONSENTRY']._serialized_start=278
  _globals['_TRANSCRIBEREQUEST_OPTIONSENTRY']._serialized_end=324
  _globals['_TRANSCRIBERESPONSE']._serialized_start=327
  _globals['_TRANSCRIBERESPONSE']._serialized_end=535
  _globals['_CAPTIONREQUEST']._serialized_start=537
  _globals['_CAPTIONREQUEST']._serialized_end=588
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=591
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=846
# @@protoc_insertion_point(module_scope)
