name: yt-text
services:
  - name: yt-text
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: nijaru/yt-text
    instance_size_slug: basic-s
    instance_count: 1
    http_port: 8080
    envs:
      - key: DOCKER_COMPOSE_FILE
        value: docker-compose.prod.yml
