name: yt-text
services:
  - name: yt-text
    dockerfile_path: Dockerfile.prod
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: nijaru/yt-text
    instance_size_slug: basic-m
    instance_count: 1
    http_port: 8080

    health_check:
      http_path: /health
      initial_delay_seconds: 40
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: DOCKER_COMPOSE_FILE
        value: docker-compose.prod.yml
      - key: TAG
        scope: RUN_TIME
        value: ${GITHUB_SHA}
      - key: ENVIRONMENT
        value: production
      - key: MALLOC_TRIM_THRESHOLD_
        value: "100000"
      - key: MALLOC_MMAP_THRESHOLD_
        value: "100000"
      - key: PYTHONMALLOC
        value: "malloc"
      - key: GOGC
        value: "10"

    alert_policy:
      name: yt-text-alerts
      rule:
        - condition: DEPLOYMENT_FAILED
        - condition: DOMAIN_FAILED
        - condition: CPU_UTILIZATION
          value: 90
          window: TEN_MINUTES
        - condition: MEM_UTILIZATION
          value: 90
          window: FIVE_MINUTES

    build_command: |
      # Clean temporary files
      rm -rf /tmp/* || true

      # Build Go binary
      GOMEMLIMIT=1024MiB CGO_ENABLED=1 go build \
        -ldflags="-w -s" \
        -gcflags='-m=2' \
        -tags 'netgo osusergo static_build' \
        -trimpath \
        -o main .

      # Install Python dependencies
      cd python && uv pip install --system
