services:
  app:
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile
    image: yt-text:latest
    environment:
      - ENV=development
      - SERVER_PORT=8080
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=60s
      - IDLE_TIMEOUT=120s
      - DEBUG=true
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_RPM=60
      - LOG_DIR=/app/logs
      - DB_PATH=/app/data/urls.db
      - SCRIPTS_PATH=/app/scripts
      - VIDEO_PROCESS_TIMEOUT=30m
      - VIDEO_MAX_DURATION=4h
      - WHISPER_MODEL=medium.en
      - PYTHON_PATH=/app/.venv/bin/python
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MIDDLEWARE_ENABLE_RECOVER=true
      - MIDDLEWARE_ENABLE_REQUEST_ID=true
      - MIDDLEWARE_ENABLE_LOGGER=true
      - MIDDLEWARE_ENABLE_TIMEOUT=false
      - MIDDLEWARE_ENABLE_CORS=true
      - MIDDLEWARE_ENABLE_RATE_LIMIT=false
      - MIDDLEWARE_ENABLE_COMPRESS=false
      - MIDDLEWARE_ENABLE_ETAG=false
      - MIDDLEWARE_ENABLE_DEBUG_MODE=true
      - USE_GRPC=true
      - GRPC_SERVER_ADDRESS=grpc:50051
    ports:
      - "8080:8080"
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      grpc:
        condition: service_healthy

  grpc:
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile
    image: yt-text:latest
    command: make grpc-server
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=medium.en
    expose:
      - "50051"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge