# docker/local/docker-compose.yml
# Note: The Docker build requires git for go mod download in the Alpine image

services:
  app:
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile
    image: yt-text:latest
    command: /usr/local/bin/yt-text
    environment:
      - ENV=development
      - SERVER_PORT=8080
      - READ_TIMEOUT=30s
      - WRITE_TIMEOUT=60s
      - IDLE_TIMEOUT=120s
      - DEBUG=true
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_RPM=60
      - LOG_DIR=/app/logs
      - DB_PATH=/app/data/urls.db
      - SCRIPTS_PATH=/app/scripts
      - VIDEO_PROCESS_TIMEOUT=30m
      - VIDEO_MAX_DURATION=4h
      - WHISPER_MODEL=medium.en
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - MIDDLEWARE_ENABLE_RECOVER=true
      - MIDDLEWARE_ENABLE_REQUEST_ID=true
      - MIDDLEWARE_ENABLE_LOGGER=true
      - MIDDLEWARE_ENABLE_TIMEOUT=false
      - MIDDLEWARE_ENABLE_CORS=true
      - MIDDLEWARE_ENABLE_RATE_LIMIT=false
      - MIDDLEWARE_ENABLE_COMPRESS=false
      - MIDDLEWARE_ENABLE_ETAG=false
      - MIDDLEWARE_ENABLE_DEBUG_MODE=true
      - USE_GRPC=true
      - GRPC_SERVER_ADDRESS=grpc:50051
    ports:
      - "8080:8080"
    volumes:
      - logs_data:/app/logs
      - db_data:/app/data
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - grpc

  grpc:
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile
    image: yt-text:latest
    command: python -m scripts.grpc.start_server 50051
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL=medium.en
      - LOG_DIR=/app/logs
      - DB_PATH=/app/data/urls.db
    volumes:
      - logs_data:/app/logs
      - db_data:/app/data
    expose:
      - "50051"
    healthcheck:
      disable: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge

volumes:
  logs_data:
  db_data: