[project]
name = "yt-text"
version = "0.1.0"
description = "Download YouTube audio and convert it to text using yt-dlp and OpenAI Whisper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "librosa>=0.10.2.post1",
    "msgpack>=1.1.0",
    "numpy>=2.0.2",
    "openai-whisper>=20240930",
    "pydub>=0.25.1",
    "torch>=2.4.1",
    "transformers>=4.46.1",
    "whisper>=1.1.10",
    "yt-dlp>=2024.10.7",
]

[tool.ruff]
target-version = "py312"
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "I",  # isort
    "UP", # pyupgrade
]
